---
# roles/zabbix_proxy/handlers/main.yml
#
# Restart, ne reload. Sintaksna greska u include fajlu sprecava
# pokretanje - bolje je da to odmah bude vidljivo.

- name: "Restartuj Zabbix proxy"
  ansible.builtin.service:
    name: "{{ _zabbix_proxy_service }}"
    state: restarted
  when: role_zabbix_proxy_service_state != 'stopped'
